### ISSUE TITLE
Newbie Question

### ISSUE THREAD

**Issue by raindog68** [apop880/SmartThings-Button#3]
Hi apop8880

New to HA and wondering where I put the code, you mention apps.yaml is that the same as configuration/yaml?

Thanks in advance

**Comment by apop880** [comment]
@raindog68 

Sorry for the delayed response, working on catching up on older issues. Do you have AppDaemon installed? That is a prerequisite for using this.

**Comment by raindog68** [comment]
All good, thanks for responding I did a work around already

Cheers
